language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx
  - windows

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user cpp-coveralls; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LD_LIBRARY_PATH=$(if [[ $CXX == "clang++" ]]; then echo -n '/usr/local/clang/lib'; fi)

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  
script:
  - ctest -C Debug -V

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E "test/test.*/.*.cpp.*"; fi
 